export interface InitialStaffData {
  staffCode: string;
  name: string;
  gender?: 'Male' | 'Female' | string;
  phone: string;
  email: string;
  role:
    | 'Makeup Artist'
    | 'Hair Stylist'
    | 'Waxing & Threading Specialist'
    | 'Fashion Stylist'
    | 'Helper'
    | 'Manicure & Pedicure Specialist'
    | 'Spa Specialist';
  specialization: string;
  joiningDate: string;
  salary: number;
  commissionPercentage: number;
  workingDays: string;
  workingHours: string;
  isActive: boolean;
}

export const INITIAL_35_STAFF: InitialStaffData[] = [
  // 1. Makeup Artists — 5 (5% commission)
  {
    staffCode: 'STF-MUA-001',
    name: 'Ananya Sen',
    gender: 'Female',
    phone: '+91 98451 10001',
    email: 'ananya.sen@veloura.in',
    role: 'Makeup Artist',
    specialization: 'Bridal & HD Makeup',
    joiningDate: '2024-01-15',
    salary: 32000,
    commissionPercentage: 5,
    workingDays: 'Mon,Tue,Wed,Thu,Fri,Sat',
    workingHours: '10:00 AM - 07:00 PM',
    isActive: true,
  },
  {
    staffCode: 'STF-MUA-002',
    name: 'Rohan Kapoor',
    gender: 'Male',
    phone: '+91 98451 10002',
    email: 'rohan.kapoor@veloura.in',
    role: 'Makeup Artist',
    specialization: 'Editorial & Party Glam',
    joiningDate: '2024-02-10',
    salary: 30000,
    commissionPercentage: 5,
    workingDays: 'Tue,Wed,Thu,Fri,Sat,Sun',
    workingHours: '11:00 AM - 08:00 PM',
    isActive: true,
  },
  {
    staffCode: 'STF-MUA-003',
    name: 'Shreya Mukherjee',
    gender: 'Female',
    phone: '+91 98451 10003',
    email: 'shreya.mukherjee@veloura.in',
    role: 'Makeup Artist',
    specialization: 'Airbrush & Engagement Makeup',
    joiningDate: '2024-03-01',
    salary: 31000,
    commissionPercentage: 5,
    workingDays: 'Mon,Wed,Thu,Fri,Sat,Sun',
    workingHours: '10:00 AM - 07:00 PM',
    isActive: true,
  },
  {
    staffCode: 'STF-MUA-004',
    name: 'Kabir Mehta',
    gender: 'Male',
    phone: '+91 98451 10004',
    email: 'kabir.mehta@veloura.in',
    role: 'Makeup Artist',
    specialization: 'Fashion Shoot & Contour Art',
    joiningDate: '2024-04-15',
    salary: 29000,
    commissionPercentage: 5,
    workingDays: 'Mon,Tue,Thu,Fri,Sat,Sun',
    workingHours: '11:30 AM - 08:30 PM',
    isActive: true,
  },
  {
    staffCode: 'STF-MUA-005',
    name: 'Tanvi Deshmukh',
    gender: 'Female',
    phone: '+91 98451 10005',
    email: 'tanvi.deshmukh@veloura.in',
    role: 'Makeup Artist',
    specialization: 'Traditional & Festive Makeup',
    joiningDate: '2024-05-20',
    salary: 28000,
    commissionPercentage: 5,
    workingDays: 'Mon,Tue,Wed,Fri,Sat,Sun',
    workingHours: '10:00 AM - 07:00 PM',
    isActive: true,
  },

  // 2. Hair Stylists — 5 (5% commission)
  {
    staffCode: 'STF-HRS-006',
    name: 'Vikram Malhotra',
    gender: 'Male',
    phone: '+91 98452 20006',
    email: 'vikram.malhotra@veloura.in',
    role: 'Hair Stylist',
    specialization: 'Precision Cuts & Fades',
    joiningDate: '2024-01-10',
    salary: 30000,
    commissionPercentage: 5,
    workingDays: 'Mon,Tue,Wed,Thu,Fri,Sat',
    workingHours: '09:30 AM - 06:30 PM',
    isActive: true,
  },
  {
    staffCode: 'STF-HRS-007',
    name: 'Pooja Sharma',
    gender: 'Female',
    phone: '+91 98452 20007',
    email: 'pooja.sharma@veloura.in',
    role: 'Hair Stylist',
    specialization: 'Keratin & Hair Botox',
    joiningDate: '2024-02-15',
    salary: 32000,
    commissionPercentage: 5,
    workingDays: 'Tue,Wed,Thu,Fri,Sat,Sun',
    workingHours: '10:00 AM - 07:00 PM',
    isActive: true,
  },
  {
    staffCode: 'STF-HRS-008',
    name: 'Arjun Nair',
    gender: 'Male',
    phone: '+91 98452 20008',
    email: 'arjun.nair@veloura.in',
    role: 'Hair Stylist',
    specialization: 'Creative Hair Coloring & Balayage',
    joiningDate: '2024-03-20',
    salary: 31000,
    commissionPercentage: 5,
    workingDays: 'Mon,Wed,Thu,Fri,Sat,Sun',
    workingHours: '10:30 AM - 07:30 PM',
    isActive: true,
  },
  {
    staffCode: 'STF-HRS-009',
    name: 'Divya Joshi',
    gender: 'Female',
    phone: '+91 98452 20009',
    email: 'divya.joshi@veloura.in',
    role: 'Hair Stylist',
    specialization: 'Smoothening & Hair Spa',
    joiningDate: '2024-04-05',
    salary: 29000,
    commissionPercentage: 5,
    workingDays: 'Mon,Tue,Thu,Fri,Sat,Sun',
    workingHours: '10:00 AM - 07:00 PM',
    isActive: true,
  },
  {
    staffCode: 'STF-HRS-010',
    name: 'Sameer Kulkarni',
    gender: 'Male',
    phone: '+91 98452 20010',
    email: 'sameer.kulkarni@veloura.in',
    role: 'Hair Stylist',
    specialization: 'Texture Styling & Blow Dry',
    joiningDate: '2024-06-01',
    salary: 27000,
    commissionPercentage: 5,
    workingDays: 'Mon,Tue,Wed,Fri,Sat,Sun',
    workingHours: '11:00 AM - 08:00 PM',
    isActive: true,
  },

  // 3. Waxing & Threading Specialists — 5 (5% commission)
  {
    staffCode: 'STF-WTS-011',
    name: 'Sunita Verma',
    gender: 'Female',
    phone: '+91 98453 30011',
    email: 'sunita.verma@veloura.in',
    role: 'Waxing & Threading Specialist',
    specialization: 'Rica Waxing & Eyebrow Architecture',
    joiningDate: '2024-01-25',
    salary: 25000,
    commissionPercentage: 5,
    workingDays: 'Mon,Tue,Wed,Thu,Fri,Sat',
    workingHours: '10:00 AM - 07:00 PM',
    isActive: true,
  },
  {
    staffCode: 'STF-WTS-012',
    name: 'Manpreet Kaur',
    gender: 'Female',
    phone: '+91 98453 30012',
    email: 'manpreet.kaur@veloura.in',
    role: 'Waxing & Threading Specialist',
    specialization: 'Full Body Painless Waxing',
    joiningDate: '2024-02-18',
    salary: 26000,
    commissionPercentage: 5,
    workingDays: 'Tue,Wed,Thu,Fri,Sat,Sun',
    workingHours: '09:30 AM - 06:30 PM',
    isActive: true,
  },
  {
    staffCode: 'STF-WTS-013',
    name: 'Rajesh Guha',
    gender: 'Male',
    phone: '+91 98453 30013',
    email: 'rajesh.guha@veloura.in',
    role: 'Waxing & Threading Specialist',
    specialization: 'Gentle Threading & Skin Prep',
    joiningDate: '2024-03-12',
    salary: 24000,
    commissionPercentage: 5,
    workingDays: 'Mon,Wed,Thu,Fri,Sat,Sun',
    workingHours: '10:00 AM - 07:00 PM',
    isActive: true,
  },
  {
    staffCode: 'STF-WTS-014',
    name: 'Rekha Patil',
    gender: 'Female',
    phone: '+91 98453 30014',
    email: 'rekha.patil@veloura.in',
    role: 'Waxing & Threading Specialist',
    specialization: 'Facial Threading & Upper Lip',
    joiningDate: '2024-04-20',
    salary: 24000,
    commissionPercentage: 5,
    workingDays: 'Mon,Tue,Thu,Fri,Sat,Sun',
    workingHours: '10:30 AM - 07:30 PM',
    isActive: true,
  },
  {
    staffCode: 'STF-WTS-015',
    name: 'Deepak Chauhan',
    gender: 'Male',
    phone: '+91 98453 30015',
    email: 'deepak.chauhan@veloura.in',
    role: 'Waxing & Threading Specialist',
    specialization: 'Sensitive Skin Strip Waxing',
    joiningDate: '2024-05-15',
    salary: 23000,
    commissionPercentage: 5,
    workingDays: 'Mon,Tue,Wed,Fri,Sat,Sun',
    workingHours: '11:00 AM - 08:00 PM',
    isActive: true,
  },

  // 4. Fashion Stylists — 5 (5% commission)
  {
    staffCode: 'STF-FSH-016',
    name: 'Aakash Singhania',
    gender: 'Male',
    phone: '+91 98454 40016',
    email: 'aakash.singhania@veloura.in',
    role: 'Fashion Stylist',
    specialization: 'Bridal Draping & Wardrobe Consulting',
    joiningDate: '2024-01-08',
    salary: 34000,
    commissionPercentage: 5,
    workingDays: 'Mon,Tue,Wed,Thu,Fri,Sat',
    workingHours: '10:00 AM - 07:00 PM',
    isActive: true,
  },
  {
    staffCode: 'STF-FSH-017',
    name: 'Meera Nambiar',
    gender: 'Female',
    phone: '+91 98454 40017',
    email: 'meera.nambiar@veloura.in',
    role: 'Fashion Stylist',
    specialization: 'Contemporary Saree Draping & Styling',
    joiningDate: '2024-02-22',
    salary: 33000,
    commissionPercentage: 5,
    workingDays: 'Tue,Wed,Thu,Fri,Sat,Sun',
    workingHours: '10:30 AM - 07:30 PM',
    isActive: true,
  },
  {
    staffCode: 'STF-FSH-018',
    name: 'Siddharth Roy',
    gender: 'Male',
    phone: '+91 98454 40018',
    email: 'siddharth.roy@veloura.in',
    role: 'Fashion Stylist',
    specialization: 'Groom Aesthetics & Event Draping',
    joiningDate: '2024-03-18',
    salary: 32000,
    commissionPercentage: 5,
    workingDays: 'Mon,Wed,Thu,Fri,Sat,Sun',
    workingHours: '11:00 AM - 08:00 PM',
    isActive: true,
  },
  {
    staffCode: 'STF-FSH-019',
    name: 'Natasha D\'Souza',
    gender: 'Female',
    phone: '+91 98454 40019',
    email: 'natasha.dsouza@veloura.in',
    role: 'Fashion Stylist',
    specialization: 'Personal Styling & Lookbook Coordination',
    joiningDate: '2024-04-10',
    salary: 31000,
    commissionPercentage: 5,
    workingDays: 'Mon,Tue,Thu,Fri,Sat,Sun',
    workingHours: '10:00 AM - 07:00 PM',
    isActive: true,
  },
  {
    staffCode: 'STF-FSH-020',
    name: 'Varun Bhatia',
    gender: 'Male',
    phone: '+91 98454 40020',
    email: 'varun.bhatia@veloura.in',
    role: 'Fashion Stylist',
    specialization: 'Fusion Outfits & Accessory Styling',
    joiningDate: '2024-05-02',
    salary: 30000,
    commissionPercentage: 5,
    workingDays: 'Mon,Tue,Wed,Fri,Sat,Sun',
    workingHours: '09:30 AM - 06:30 PM',
    isActive: true,
  },

  // 5. Helpers — 5 (4% commission)
  {
    staffCode: 'STF-HLP-021',
    name: 'Ramesh Yadav',
    gender: 'Male',
    phone: '+91 98455 50021',
    email: 'ramesh.yadav@veloura.in',
    role: 'Helper',
    specialization: 'Shampoo Station & Product Assist',
    joiningDate: '2024-01-05',
    salary: 18000,
    commissionPercentage: 4,
    workingDays: 'Mon,Tue,Wed,Thu,Fri,Sat',
    workingHours: '09:00 AM - 06:00 PM',
    isActive: true,
  },
  {
    staffCode: 'STF-HLP-022',
    name: 'Geeta Devi',
    gender: 'Female',
    phone: '+91 98455 50022',
    email: 'geeta.devi@veloura.in',
    role: 'Helper',
    specialization: 'Towels, Hygiene & Client Refreshments',
    joiningDate: '2024-01-20',
    salary: 18000,
    commissionPercentage: 4,
    workingDays: 'Tue,Wed,Thu,Fri,Sat,Sun',
    workingHours: '09:30 AM - 06:30 PM',
    isActive: true,
  },
  {
    staffCode: 'STF-HLP-023',
    name: 'Suresh Paswan',
    gender: 'Male',
    phone: '+91 98455 50023',
    email: 'suresh.paswan@veloura.in',
    role: 'Helper',
    specialization: 'Equipment Sanitization & Floor Assist',
    joiningDate: '2024-02-14',
    salary: 17500,
    commissionPercentage: 4,
    workingDays: 'Mon,Wed,Thu,Fri,Sat,Sun',
    workingHours: '10:00 AM - 07:00 PM',
    isActive: true,
  },
  {
    staffCode: 'STF-HLP-024',
    name: 'Lakshmi Bai',
    gender: 'Female',
    phone: '+91 98455 50024',
    email: 'lakshmi.bai@veloura.in',
    role: 'Helper',
    specialization: 'Hair Wash Assist & Salon Maintenance',
    joiningDate: '2024-03-05',
    salary: 18500,
    commissionPercentage: 4,
    workingDays: 'Mon,Tue,Thu,Fri,Sat,Sun',
    workingHours: '10:30 AM - 07:30 PM',
    isActive: true,
  },
  {
    staffCode: 'STF-HLP-025',
    name: 'Mohan Lal',
    gender: 'Male',
    phone: '+91 98455 50025',
    email: 'mohan.lal@veloura.in',
    role: 'Helper',
    specialization: 'Inventory Unpacking & Client Assistance',
    joiningDate: '2024-04-01',
    salary: 17000,
    commissionPercentage: 4,
    workingDays: 'Mon,Tue,Wed,Fri,Sat,Sun',
    workingHours: '11:00 AM - 08:00 PM',
    isActive: true,
  },

  // 6. Manicure & Pedicure Specialists — 5 (5% commission)
  {
    staffCode: 'STF-MPS-026',
    name: 'Priya Raghavan',
    gender: 'Female',
    phone: '+91 98456 60026',
    email: 'priya.raghavan@veloura.in',
    role: 'Manicure & Pedicure Specialist',
    specialization: 'Gel Nails, Nail Art & Paraffin Spa',
    joiningDate: '2024-01-18',
    salary: 28000,
    commissionPercentage: 5,
    workingDays: 'Mon,Tue,Wed,Thu,Fri,Sat',
    workingHours: '10:00 AM - 07:00 PM',
    isActive: true,
  },
  {
    staffCode: 'STF-MPS-027',
    name: 'Nitin Choudhary',
    gender: 'Male',
    phone: '+91 98456 60027',
    email: 'nitin.choudhary@veloura.in',
    role: 'Manicure & Pedicure Specialist',
    specialization: 'Classic French Tips & Foot Reflexology',
    joiningDate: '2024-02-12',
    salary: 27000,
    commissionPercentage: 5,
    workingDays: 'Tue,Wed,Thu,Fri,Sat,Sun',
    workingHours: '09:30 AM - 06:30 PM',
    isActive: true,
  },
  {
    staffCode: 'STF-MPS-028',
    name: 'Neha Agarwal',
    gender: 'Female',
    phone: '+91 98456 60028',
    email: 'neha.agarwal@veloura.in',
    role: 'Manicure & Pedicure Specialist',
    specialization: 'Spa Manicure & Pedicure Rejuvenation',
    joiningDate: '2024-03-08',
    salary: 29000,
    commissionPercentage: 5,
    workingDays: 'Mon,Wed,Thu,Fri,Sat,Sun',
    workingHours: '10:30 AM - 07:30 PM',
    isActive: true,
  },
  {
    staffCode: 'STF-MPS-029',
    name: 'Karan Bhatt',
    gender: 'Male',
    phone: '+91 98456 60029',
    email: 'karan.bhatt@veloura.in',
    role: 'Manicure & Pedicure Specialist',
    specialization: 'Ingrown Nail Care & Cuticle Therapy',
    joiningDate: '2024-04-14',
    salary: 27500,
    commissionPercentage: 5,
    workingDays: 'Mon,Tue,Thu,Fri,Sat,Sun',
    workingHours: '11:00 AM - 08:00 PM',
    isActive: true,
  },
  {
    staffCode: 'STF-MPS-030',
    name: 'Shalini Pillai',
    gender: 'Female',
    phone: '+91 98456 60030',
    email: 'shalini.pillai@veloura.in',
    role: 'Manicure & Pedicure Specialist',
    specialization: 'Bridal Nail Extensions & Chrome Finishes',
    joiningDate: '2024-05-19',
    salary: 30000,
    commissionPercentage: 5,
    workingDays: 'Mon,Tue,Wed,Fri,Sat,Sun',
    workingHours: '10:00 AM - 07:00 PM',
    isActive: true,
  },

  // 7. Spa Specialists — 5 (5% commission)
  {
    staffCode: 'STF-SPA-031',
    name: 'Aditya Kashyap',
    gender: 'Male',
    phone: '+91 98457 70031',
    email: 'aditya.kashyap@veloura.in',
    role: 'Spa Specialist',
    specialization: 'Ayurvedic Scalp Massage & Deep Tissue Relaxation',
    joiningDate: '2024-01-12',
    salary: 32000,
    commissionPercentage: 5,
    workingDays: 'Mon,Tue,Wed,Thu,Fri,Sat',
    workingHours: '10:00 AM - 07:00 PM',
    isActive: true,
  },
  {
    staffCode: 'STF-SPA-032',
    name: 'Swati Hegde',
    gender: 'Female',
    phone: '+91 98457 70032',
    email: 'swati.hegde@veloura.in',
    role: 'Spa Specialist',
    specialization: 'Aromatherapy & Herbal Hair Spa Infusions',
    joiningDate: '2024-02-20',
    salary: 31000,
    commissionPercentage: 5,
    workingDays: 'Tue,Wed,Thu,Fri,Sat,Sun',
    workingHours: '10:30 AM - 07:30 PM',
    isActive: true,
  },
  {
    staffCode: 'STF-SPA-033',
    name: 'Nikhil Trivedi',
    gender: 'Male',
    phone: '+91 98457 70033',
    email: 'nikhil.trivedi@veloura.in',
    role: 'Spa Specialist',
    specialization: 'Stress-Relief Head & Shoulder Therapy',
    joiningDate: '2024-03-15',
    salary: 30000,
    commissionPercentage: 5,
    workingDays: 'Mon,Wed,Thu,Fri,Sat,Sun',
    workingHours: '11:00 AM - 08:00 PM',
    isActive: true,
  },
  {
    staffCode: 'STF-SPA-034',
    name: 'Bhavna Goswami',
    gender: 'Female',
    phone: '+91 98457 70034',
    email: 'bhavna.goswami@veloura.in',
    role: 'Spa Specialist',
    specialization: 'Detoxifying Scalp Steam & Moroccan Oil Spa',
    joiningDate: '2024-04-18',
    salary: 31500,
    commissionPercentage: 5,
    workingDays: 'Mon,Tue,Thu,Fri,Sat,Sun',
    workingHours: '10:00 AM - 07:00 PM',
    isActive: true,
  },
  {
    staffCode: 'STF-SPA-035',
    name: 'Tarun Somani',
    gender: 'Male',
    phone: '+91 98457 70035',
    email: 'tarun.somani@veloura.in',
    role: 'Spa Specialist',
    specialization: 'Hot Oil Ayurvedic Head & Neck Massage',
    joiningDate: '2024-05-25',
    salary: 29500,
    commissionPercentage: 5,
    workingDays: 'Mon,Tue,Wed,Fri,Sat,Sun',
    workingHours: '09:30 AM - 06:30 PM',
    isActive: true,
  },
];
